<form action="/users/<?= htmlspecialchars($user['id']) ?>" method="post">
    <input type="hidden" name="_METHOD" value="PATCH">
    <div>
        <label>
            Имя *
            <input type="text" name="user[nickname]" value="<?= htmlspecialchars($user['nickname'] ?? '') ?>">
        </label>
    <!-- Чтобы в форму подставлялись возникающие ошибки и значения полей, 
    введенные пользователем, добавляем следующее -->
        <?php if (isset($errors['nickname'])): ?>
            <div><?= $errors['nickname'] ?></div>
        <?php endif ?>
    </div>
    <div>
        <label>
            Email *
        <input type="email" name="user[email]" value="<?= htmlspecialchars($user['email'] ?? '') ?>">
        </label>
    <!-- Чтобы в форму подставлялись возникающие ошибки и значения полей, 
    введенные пользователем, добавляем следующее -->
        <?php if (isset($errors['email'])): ?>
            <div><?= $errors['email'] ?></div>
        <?php endif ?>
    </div>
    <input type="submit" value="Update">
</form>