<!-- Шаблон для обработчика get /users, который отображает пользователей и почту -->
<form action="/users" method="get">
  <input type="search" name="nickname" value="<?= htmlspecialchars($nickname) ?>" />
  <input type="submit" value="Search" />
</form>

<?php if (count($flash) > 0) : ?>
    <ul>
    <?php foreach ($flash as $messages) : ?>
        <?php foreach ($messages as $message) : ?>
            <li><?= $message ?></li>
        <?php endforeach ?>
    <?php endforeach ?>
    </ul>
<?php endif ?>

<table>
    <?php foreach ($users as $user) : ?>
        <tr>
            <td>
                <?= $user['id'] ?>
            </td>
            <td>
                <?= $user['nickname'] ?>
            </td>
            <td>
                <?= $user['email'] ?>
            </td>
        </tr>
    <?php endforeach ?>
</table>
