<a href="/users/new">Добавить нового пользователя</a>

<!-- Выводим flash сообщения при удачном добавлении нового пользователя -->
<?php if (count($flash) > 0) : ?>
    <style>
        li {
            color: green; /* задаем цыет flash сообщения */
        }
    </style>
    <ul>
    <?php foreach ($flash as $messages) : ?>
        <?php foreach ($messages as $message) : ?>
            <li><?= $message ?></li>
        <?php endforeach ?>
    <?php endforeach ?>
    </ul>
<?php endif ?>

<!-- Шаблон для обработчика get /users, который отображает пользователей и почту -->
<form action="/users" method="get">
  <input type="search" name="nickname" value="<?= htmlspecialchars($nickname) ?>" />
  <input type="submit" value="Search" />
</form>

<table>
    <?php foreach ($users as $user) : ?>
        <?php if ($user) : ?>
            <tr>
                <td>
                    <?= htmlspecialchars($user['id']) ?>
                </td>
                <td>
                    <a href="/users/<?= $user['id'] ?>/edit"><?= htmlspecialchars($user['nickname']) ?></a>
                </td>
                <td>
                    <?= htmlspecialchars($user['email']) ?></a>
                </td>
                <td>
                    <form action="/users/<?= $user['id'] ?>" method="post">
                        <input type="hidden" name="_METHOD" value="DELETE">
                        <input type="submit" value="Delete">
                    </form>
                </td>
            </tr>
        <?php endif; ?>
    <?php endforeach ?>
</table>

<a href="/">Войти/Выйти</a>