<?php if (count($flash) > 0): ?>
    <ul>
        <?php foreach ($flash as $messages): ?>
            <?php foreach ($messages as $message): ?>
                <li><?= $message ?></li>
            <?php endforeach ?>
        <?php endforeach ?>
    </ul>
<?php endif ?>
<?php if ($user): ?>
    <h1>Hello, <?= htmlspecialchars($user) ?>!</h1>
    <form action="<?= $url ?>" method="post">
        <input type="hidden" name="_METHOD" value="DELETE">
        <input type="submit" value="Sign Out">
    </form>
<?php else: ?>
    <h1>Sign In</h1>
    <form action="<?= $url ?>" method="post">
        <p>
            <label>
                Name
                <input type="text" required name="user[name]">
            </label>
        </p>
        <p>
            <label>
                Email
                <input type="email" required name="user[email]">
            </label>
        </p>
        <input type="submit" value="Sign In">
    </form>
<?php endif ?>

<a href="/users">Список пользователей</a>